"""Alembic environment.

The database URL comes from validated settings, never from alembic.ini — one
source of truth for connection details, and no chance of a migration running
against a URL that differs from the one the application uses.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from mmp_core.settings import load_settings
from mmp_db.base import Base
from mmp_db.models import *  # noqa: F403 — importing registers every table
from mmp_db.rollups import TABLES as ROLLUP_TABLES
from sqlalchemy import create_engine, pool

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _sync_url() -> str:
    settings = load_settings(service_name="alembic")
    # Migrations run synchronously: DDL is serialised anyway, and psycopg's
    # simpler failure modes are worth more here than async throughput.
    return str(settings.database_url).replace("postgresql+asyncpg://", "postgresql+psycopg://")


def run_migrations_offline() -> None:
    context.configure(
        url=_sync_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    engine = create_engine(_sync_url(), poolclass=pool.NullPool)
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            # Partitioned tables and their children are managed by
            # mmp_db.partitions, not by autogenerate. Without this filter every
            # autogenerated migration would try to drop yesterday's partitions.
            include_object=_include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


def _include_object(obj: object, name: str | None, type_: str, *_args: object) -> bool:
    if type_ != "table" or name is None:
        return True
    # Tables managed outside the ORM: the partitioned event tables (created by
    # mmp_db.partitions) and the rollups (created by mmp_db.rollups). Without
    # this, every autogenerated migration would try to drop them — autogenerate
    # compares against the ORM metadata, and they are deliberately not in it.
    unmanaged = {"clicks", "events"} | set(ROLLUP_TABLES)
    return not (name in unmanaged or name.startswith(("clicks_", "events_")))


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
