"""app consent mode

Revision ID: 3e7fcad0d909
Revises: 88313e020033
Created: 2026-09-08 11:09:13.801832+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401 — used by generated columns

revision: str = "3e7fcad0d909"
down_revision: str | None = "88313e020033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apps",
        sa.Column(
            "consent_mode", sa.String(length=20), server_default="permissive", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("apps", "consent_mode")
    # ### end Alembic commands ###
