"""webhook deliveries

Revision ID: 34493ebdaa7e
Revises: 26e63884a540
Created: 2026-09-08 07:07:02.602712+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from mmp_db.rls import enable_rls_sql, grant_sql
from sqlalchemy.dialects import postgresql  # noqa: F401 — used by generated columns

revision: str = "34493ebdaa7e"
down_revision: str | None = "26e63884a540"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("webhook_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
        sa.Column("request_url", sa.Text(), nullable=True),
        sa.Column("request_body", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'in_flight', 'delivered', 'failed', 'abandoned')",
            name=op.f("ck_webhook_deliveries_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhook_deliveries_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
            name=op.f("fk_webhook_deliveries_webhook_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_deliveries")),
        sa.UniqueConstraint(
            "webhook_id", "event_id", name=op.f("uq_webhook_deliveries_webhook_id_event_id")
        ),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_organization_id"),
        "webhook_deliveries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_deliveries_recent",
        "webhook_deliveries",
        ["webhook_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_webhook_deliveries_retry",
        "webhook_deliveries",
        ["next_retry_at"],
        unique=False,
        postgresql_where="status = 'failed'",
    )
    op.create_index(
        op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False
    )
    # ### end Alembic commands ###

    # A tenant table: same isolation as everything else. Reusing the shared
    # helpers rather than restating the policy, so the rule has one definition.
    for statement in enable_rls_sql("webhook_deliveries"):
        op.execute(statement)
    for statement in grant_sql("webhook_deliveries"):
        op.execute(statement)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.drop_index(
        "ix_webhook_deliveries_retry",
        table_name="webhook_deliveries",
        postgresql_where="status = 'failed'",
    )
    op.drop_index("ix_webhook_deliveries_recent", table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_organization_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    # ### end Alembic commands ###
