"""business tables

Revision ID: be753243702d
Revises:
Created: 2026-09-07 16:57:51.910273+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "be753243702d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "pipeline_audit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("bucket_hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.Column(
            "recorded_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_audit")),
        sa.UniqueConstraint(
            "app_id",
            "bucket_hour",
            "stage",
            name=op.f("uq_pipeline_audit_app_id_bucket_hour_stage"),
        ),
    )
    op.create_index(op.f("ix_pipeline_audit_app_id"), "pipeline_audit", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_pipeline_audit_bucket_hour"), "pipeline_audit", ["bucket_hour"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "apps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("android_package_name", sa.String(length=255), nullable=True),
        sa.Column("ios_bundle_id", sa.String(length=255), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("install_window_days", sa.SmallInteger(), nullable=False),
        sa.Column("event_window_days", sa.SmallInteger(), nullable=False),
        sa.Column("session_timeout_minutes", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('android', 'ios', 'cross_platform')", name=op.f("ck_apps_platform_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'disabled')", name=op.f("ck_apps_status_valid")
        ),
        sa.CheckConstraint(
            "install_window_days BETWEEN 1 AND 30 AND event_window_days BETWEEN 1 AND 90",
            name=op.f("ck_apps_attribution_windows_sane"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_apps_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_apps")),
    )
    op.create_index(
        op.f("ix_apps_android_package_name"), "apps", ["android_package_name"], unique=False
    )
    op.create_index(op.f("ix_apps_ios_bundle_id"), "apps", ["ios_bundle_id"], unique=False)
    op.create_index(op.f("ix_apps_organization_id"), "apps", ["organization_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("previous_hash", postgresql.BYTEA(), nullable=True),
        sa.Column("entry_hash", postgresql.BYTEA(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_log_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_org_time", "audit_log", ["organization_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_organization_id"), "audit_log", ["organization_id"], unique=False
    )
    op.create_table(
        "organization_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')",
            name=op.f("ck_organization_members_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_members_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_organization_members_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_members")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            name=op.f("uq_organization_members_organization_id_user_id"),
        ),
    )
    op.create_index(
        op.f("ix_organization_members_organization_id"),
        "organization_members",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_members_user_id"), "organization_members", ["user_id"], unique=False
    )
    op.create_table(
        "provider_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("credentials_ciphertext", postgresql.BYTEA(), nullable=False),
        sa.Column("credentials_nonce", postgresql.BYTEA(), nullable=False),
        sa.Column("wrapped_dek", postgresql.BYTEA(), nullable=False),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'error')",
            name=op.f("ck_provider_integrations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_provider_integrations_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_integrations")),
        sa.UniqueConstraint(
            "organization_id",
            "provider",
            "name",
            name=op.f("uq_provider_integrations_organization_id_provider_name"),
        ),
    )
    op.create_index(
        op.f("ix_provider_integrations_organization_id"),
        "provider_integrations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("secret_ciphertext", postgresql.BYTEA(), nullable=False),
        sa.Column("secret_nonce", postgresql.BYTEA(), nullable=False),
        sa.Column("wrapped_dek", postgresql.BYTEA(), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("consecutive_failures", sa.SmallInteger(), nullable=False),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhooks_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhooks")),
    )
    op.create_index(
        op.f("ix_webhooks_organization_id"), "webhooks", ["organization_id"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", postgresql.BYTEA(), nullable=False),
        sa.Column("pepper_version", sa.SmallInteger(), nullable=False),
        sa.Column("environment", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "environment IN ('dev', 'prod')", name=op.f("ck_api_keys_environment_valid")
        ),
        sa.CheckConstraint("kind IN ('sdk', 's2s')", name=op.f("ck_api_keys_kind_valid")),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_api_keys_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_api_keys_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_api_keys_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index(op.f("ix_api_keys_app_id"), "api_keys", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_api_keys_organization_id"), "api_keys", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_api_keys_prefix_active",
        "api_keys",
        ["key_prefix"],
        unique=False,
        postgresql_where="status = 'active'",
    )
    op.create_table(
        "attributions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("install_key", sa.String(length=255), nullable=False),
        sa.Column("anonymous_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("click_id", sa.UUID(), nullable=True),
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("tracking_link_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("medium", sa.String(length=120), nullable=True),
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attributed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_days", sa.SmallInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('referrer', 'click_id', 'device_match', 'organic', 'probabilistic')",
            name=op.f("ck_attributions_method_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_attributions_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_attributions_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["attributions.id"],
            name=op.f("fk_attributions_superseded_by"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attributions")),
    )
    op.create_index(op.f("ix_attributions_app_id"), "attributions", ["app_id"], unique=False)
    op.create_index(
        "ix_attributions_click_id",
        "attributions",
        ["click_id"],
        unique=False,
        postgresql_where="click_id IS NOT NULL",
    )
    op.create_index(
        op.f("ix_attributions_expires_at"), "attributions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_attributions_organization_id"), "attributions", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_attributions_user_id"), "attributions", ["user_id"], unique=False)
    op.create_index(
        "uq_attributions_install_key_current",
        "attributions",
        ["app_id", "install_key"],
        unique=True,
        postgresql_where="superseded_by IS NULL",
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=True),
        sa.Column("medium", sa.String(length=120), nullable=True),
        sa.Column("external_campaign_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'archived')", name=op.f("ck_campaigns_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_campaigns_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_campaigns_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
        sa.UniqueConstraint("app_id", "name", name=op.f("uq_campaigns_app_id_name")),
    )
    op.create_index(op.f("ix_campaigns_app_id"), "campaigns", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_campaigns_external_campaign_id"),
        "campaigns",
        ["external_campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaigns_organization_id"), "campaigns", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_campaigns_source"), "campaigns", ["source"], unique=False)
    op.create_table(
        "consent_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("anonymous_id", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "purpose IN ('analytics', 'attribution', 'advertising')",
            name=op.f("ck_consent_states_purpose_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('unknown', 'granted', 'denied')", name=op.f("ck_consent_states_state_valid")
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_consent_states_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_consent_states_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consent_states")),
        sa.UniqueConstraint(
            "app_id",
            "anonymous_id",
            "purpose",
            name=op.f("uq_consent_states_app_id_anonymous_id_purpose"),
        ),
    )
    op.create_index(op.f("ix_consent_states_app_id"), "consent_states", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_consent_states_organization_id"),
        "consent_states",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "conversion_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("event_name", sa.String(length=120), nullable=False),
        sa.Column("conversion_value", sa.SmallInteger(), nullable=False),
        sa.Column("coarse_value", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "conversion_value BETWEEN 0 AND 63",
            name=op.f("ck_conversion_mappings_conversion_value_range"),
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_conversion_mappings_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_conversion_mappings_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversion_mappings")),
        sa.UniqueConstraint(
            "app_id",
            "platform",
            "event_name",
            name=op.f("uq_conversion_mappings_app_id_platform_event_name"),
        ),
    )
    op.create_index(
        op.f("ix_conversion_mappings_app_id"), "conversion_mappings", ["app_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversion_mappings_organization_id"),
        "conversion_mappings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "deep_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("fallback_url", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_deep_links_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_deep_links_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deep_links")),
        sa.UniqueConstraint("code", name=op.f("uq_deep_links_code")),
    )
    op.create_index(op.f("ix_deep_links_app_id"), "deep_links", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_deep_links_organization_id"), "deep_links", ["organization_id"], unique=False
    )
    op.create_table(
        "postback_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("provider_integration_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("trigger_event", sa.String(length=120), nullable=False),
        sa.Column("method", sa.String(length=4), nullable=False),
        sa.Column("url_template", sa.Text(), nullable=False),
        sa.Column("body_template", sa.Text(), nullable=True),
        sa.Column("headers_ciphertext", postgresql.BYTEA(), nullable=True),
        sa.Column("headers_nonce", postgresql.BYTEA(), nullable=True),
        sa.Column("wrapped_dek", postgresql.BYTEA(), nullable=True),
        sa.Column("success_status_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requires_attribution", sa.Boolean(), nullable=False),
        sa.Column("is_sandbox", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('GET', 'POST')", name=op.f("ck_postback_rules_method_valid")
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_postback_rules_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_postback_rules_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_integration_id"],
            ["provider_integrations.id"],
            name=op.f("fk_postback_rules_provider_integration_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_postback_rules")),
    )
    op.create_index(
        "ix_postback_rules_app_event", "postback_rules", ["app_id", "trigger_event"], unique=False
    )
    op.create_index(op.f("ix_postback_rules_app_id"), "postback_rules", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_postback_rules_organization_id"),
        "postback_rules",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "usage_rollup",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("bucket_hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric", sa.String(length=40), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_usage_rollup_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_rollup_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_rollup")),
        sa.UniqueConstraint(
            "organization_id",
            "app_id",
            "bucket_hour",
            "metric",
            name=op.f("uq_usage_rollup_organization_id_app_id_bucket_hour_metric"),
        ),
    )
    op.create_index(op.f("ix_usage_rollup_app_id"), "usage_rollup", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_usage_rollup_bucket_hour"), "usage_rollup", ["bucket_hour"], unique=False
    )
    op.create_index(
        op.f("ix_usage_rollup_organization_id"), "usage_rollup", ["organization_id"], unique=False
    )
    op.create_table(
        "postback_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("postback_rule_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), nullable=False),
        sa.Column("request_url", sa.Text(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'in_flight', 'delivered', 'failed', 'abandoned')",
            name=op.f("ck_postback_deliveries_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_postback_deliveries_organization_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["postback_rule_id"],
            ["postback_rules.id"],
            name=op.f("fk_postback_deliveries_postback_rule_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_postback_deliveries")),
        sa.UniqueConstraint(
            "postback_rule_id",
            "event_id",
            name=op.f("uq_postback_deliveries_postback_rule_id_event_id"),
        ),
    )
    op.create_index(
        op.f("ix_postback_deliveries_organization_id"),
        "postback_deliveries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_postback_deliveries_postback_rule_id"),
        "postback_deliveries",
        ["postback_rule_id"],
        unique=False,
    )
    op.create_index(
        "ix_postback_deliveries_retry",
        "postback_deliveries",
        ["next_retry_at"],
        unique=False,
        postgresql_where="status = 'failed'",
    )
    op.create_table(
        "tracking_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("tracking_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("android_url", sa.Text(), nullable=True),
        sa.Column("ios_url", sa.Text(), nullable=True),
        sa.Column("fallback_url", sa.Text(), nullable=False),
        sa.Column("deep_link_path", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'disabled')", name=op.f("ck_tracking_links_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["app_id"], ["apps.id"], name=op.f("fk_tracking_links_app_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_tracking_links_campaign_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_tracking_links_organization_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_links")),
        sa.UniqueConstraint("tracking_code", name=op.f("uq_tracking_links_tracking_code")),
    )
    op.create_index(op.f("ix_tracking_links_app_id"), "tracking_links", ["app_id"], unique=False)
    op.create_index(
        op.f("ix_tracking_links_campaign_id"), "tracking_links", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_tracking_links_organization_id"),
        "tracking_links",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracking_links_organization_id"), table_name="tracking_links")
    op.drop_index(op.f("ix_tracking_links_campaign_id"), table_name="tracking_links")
    op.drop_index(op.f("ix_tracking_links_app_id"), table_name="tracking_links")
    op.drop_table("tracking_links")
    op.drop_index(
        "ix_postback_deliveries_retry",
        table_name="postback_deliveries",
        postgresql_where="status = 'failed'",
    )
    op.drop_index(op.f("ix_postback_deliveries_postback_rule_id"), table_name="postback_deliveries")
    op.drop_index(op.f("ix_postback_deliveries_organization_id"), table_name="postback_deliveries")
    op.drop_table("postback_deliveries")
    op.drop_index(op.f("ix_usage_rollup_organization_id"), table_name="usage_rollup")
    op.drop_index(op.f("ix_usage_rollup_bucket_hour"), table_name="usage_rollup")
    op.drop_index(op.f("ix_usage_rollup_app_id"), table_name="usage_rollup")
    op.drop_table("usage_rollup")
    op.drop_index(op.f("ix_postback_rules_organization_id"), table_name="postback_rules")
    op.drop_index(op.f("ix_postback_rules_app_id"), table_name="postback_rules")
    op.drop_index("ix_postback_rules_app_event", table_name="postback_rules")
    op.drop_table("postback_rules")
    op.drop_index(op.f("ix_deep_links_organization_id"), table_name="deep_links")
    op.drop_index(op.f("ix_deep_links_app_id"), table_name="deep_links")
    op.drop_table("deep_links")
    op.drop_index(op.f("ix_conversion_mappings_organization_id"), table_name="conversion_mappings")
    op.drop_index(op.f("ix_conversion_mappings_app_id"), table_name="conversion_mappings")
    op.drop_table("conversion_mappings")
    op.drop_index(op.f("ix_consent_states_organization_id"), table_name="consent_states")
    op.drop_index(op.f("ix_consent_states_app_id"), table_name="consent_states")
    op.drop_table("consent_states")
    op.drop_index(op.f("ix_campaigns_source"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_organization_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_external_campaign_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_app_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(
        "uq_attributions_install_key_current",
        table_name="attributions",
        postgresql_where="superseded_by IS NULL",
    )
    op.drop_index(op.f("ix_attributions_user_id"), table_name="attributions")
    op.drop_index(op.f("ix_attributions_organization_id"), table_name="attributions")
    op.drop_index(op.f("ix_attributions_expires_at"), table_name="attributions")
    op.drop_index(
        "ix_attributions_click_id",
        table_name="attributions",
        postgresql_where="click_id IS NOT NULL",
    )
    op.drop_index(op.f("ix_attributions_app_id"), table_name="attributions")
    op.drop_table("attributions")
    op.drop_index(
        "ix_api_keys_prefix_active", table_name="api_keys", postgresql_where="status = 'active'"
    )
    op.drop_index(op.f("ix_api_keys_organization_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_app_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_webhooks_organization_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(
        op.f("ix_provider_integrations_organization_id"), table_name="provider_integrations"
    )
    op.drop_table("provider_integrations")
    op.drop_index(op.f("ix_organization_members_user_id"), table_name="organization_members")
    op.drop_index(
        op.f("ix_organization_members_organization_id"), table_name="organization_members"
    )
    op.drop_table("organization_members")
    op.drop_index(op.f("ix_audit_log_organization_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_org_time", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_apps_organization_id"), table_name="apps")
    op.drop_index(op.f("ix_apps_ios_bundle_id"), table_name="apps")
    op.drop_index(op.f("ix_apps_android_package_name"), table_name="apps")
    op.drop_table("apps")
    op.drop_table("users")
    op.drop_index(op.f("ix_pipeline_audit_bucket_hour"), table_name="pipeline_audit")
    op.drop_index(op.f("ix_pipeline_audit_app_id"), table_name="pipeline_audit")
    op.drop_table("pipeline_audit")
    op.drop_table("organizations")
    # ### end Alembic commands ###
